DataSources:
  Spotify:
    API:
      ApiKey: xyz 
      URL: spotify.com/api
      Request: True
      Webhook: False
      Historical: False
    Database:
      Type: Spotify
  Up:
    API:
      ApiKey: xyz 
      URL: up.com/api
      Request: False
      Webhook: True
      Historical: True
    Database:
      Type: Spotify    
  

Dashboards:
  Weekly:
    Name: Weekly
    Datasources:
      Tables:
      - Spotify
      - UP
  
  Historical:
    Name: Historical
    Datasources:
      Tables:
      - UP

